source 'http://rubygems.org'

gem 'rails', '3.2.21'
gem 'rails-secrets'
gem 'authlogic'
gem 'paperclip', '~> 3.0'
gem 'fastercsv'
gem 'mysql2'
gem 'net-ldap'
gem 'rails-csv-fixtures'
gem 'sequel'
gem 'jquery-rails'
gem 'uglifier'
gem 'libv8', '~> 3.11.8'
gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git', :branch => 'bootstrap3'
gem 'therubyracer'
gem 'less-rails'
gem 'will_paginate', '~> 3.0'
gem 'will_paginate-bootstrap'
gem 'bootstrap-datepicker-rails', '~> 1.3.1.1'
gem 'bootstrap-multiselect-rails'
